// Auto-generated by MutaCI — GhostBuster
// These tests fill behavioral gaps found by mutation testing

import { applyDiscount } from '../src/pricing';
import { calculateSeasonalPrice } from '../src/pricing';

// Gap: No test verifies that 0% discount returns the original price unchanged
describe('applyDiscount — boundary: 0% discount', () => {
  it('returns original price unchanged when discount is 0%', () => {
    expect(applyDiscount(100, { type: 'percentage', value: 0 })).toBe(100);
  });
});

// Gap: No test verifies that negative percentage discount raises an error
describe('applyDiscount — validation: negative discount', () => {
  it('throws when percentage discount is negative', () => {
    expect(() =>
      applyDiscount(100, { type: 'percentage', value: -10 })
    ).toThrow('Invalid percentage discount');
  });
});

// Gap: No test verifies that a 100% discount results in $0, not a negative price
describe('applyDiscount — boundary: 100% discount', () => {
  it('returns 0 (not negative) when discount is 100%', () => {
    const result = applyDiscount(50, { type: 'percentage', value: 100 });
    expect(result).toBe(0);
    expect(result).toBeGreaterThanOrEqual(0);
  });
});

// Gap: No test verifies discount stacking order — applying fixed then % gives different result than % then fixed
describe('calculateSeasonalPrice — discount stacking order', () => {
  it('fixed-then-percentage differs from percentage-then-fixed', () => {
    const fixedFirst = calculateSeasonalPrice(100, 1, [
      { type: 'fixed', value: 20 },
      { type: 'percentage', value: 10 },
    ]);
    const pctFirst = calculateSeasonalPrice(100, 1, [
      { type: 'percentage', value: 10 },
      { type: 'fixed', value: 20 },
    ]);
    // $100 - $20 = $80 * 0.9 = $72  vs  $100 * 0.9 = $90 - $20 = $70
    expect(fixedFirst.discountedPrice).toBe(72);
    expect(pctFirst.discountedPrice).toBe(70);
    expect(fixedFirst.discountedPrice).not.toBe(pctFirst.discountedPrice);
  });
});

