"""Subagent A: EnvironmentAgent — generate .env.bugport from snapshot env_spec."""

from __future__ import annotations

from ...schemas.bugport import BugSnapshot

# Keys that must never appear in the env file even if present in snapshot
_PII_ENV_KEYS = {"password", "secret", "token", "api_key", "authorization", "private_key"}


def generate_env_file(snapshot: BugSnapshot) -> str:
    """Produce .env.bugport content from the snapshot env spec."""
    lines = [
        "# .env.bugport — generated by BugPort EnvironmentAgent",
        f"# git SHA: {snapshot.git_sha}",
        f"# Snapshot: {snapshot.snapshot_id}",
        f"# Service: {snapshot.service}",
        "",
    ]
    for key, value in snapshot.env_spec.items():
        if any(pii in key.lower() for pii in _PII_ENV_KEYS):
            continue
        lines.append(f"{key}={value}")
    lines += [
        "",
        "# Add your local secrets below (never commit):",
        "DATABASE_URL=postgresql://localhost/bugport_repro",
    ]
    return "\n".join(lines)


async def run(snapshot: BugSnapshot) -> str:
    """Return .env.bugport file contents."""
    return generate_env_file(snapshot)
